name = "vpn-tunnel"
main = "worker.js"
compatibility_date = "2023-10-30"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }

[[kv_namespaces]]
binding = "USER_PROXY_KV"
id = "2c95adbef02644ce878598ee3f59cb06" # Replace with your KV namespace ID

[env.production.kv_namespaces]
USER_PROXY_KV = { id = "2c95adbef02644ce878598ee3f59cb06" }

[env.staging.kv_namespaces]
USER_PROXY_KV = { id = "2c95adbef02644ce878598ee3f59cb06" }
