name = "vpn-tunnel"
main = "worker.js"
compatibility_date = "2023-10-30"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }

[[kv_namespaces]]
binding = "USER_PROXY_KV"
id = "your-user-proxy-kv-namespace-id" # Replace with your KV namespace ID

[env.production.kv_namespaces]
USER_PROXY_KV = { id = "your-user-proxy-kv-namespace-id" }

[env.staging.kv_namespaces]
USER_PROXY_KV = { id = "your-staging-user-proxy-kv-namespace-id" }
